import path from "node:path";
import { dmnoTypeFor } from "./classify.js";

export function generateDmnoDraft(report) {
  const serviceName = path.basename(report.root).replace(/[^a-zA-Z0-9_-]/g, "-") || "app";
  const lines = [
    "import { DmnoBaseTypes, defineDmnoService } from 'dmno';",
    "",
    "// Generated by env-mapper-mcp. Review before committing.",
    "// Secret values are intentionally not included.",
    "export default defineDmnoService({",
    `  name: '${escapeString(serviceName)}',`,
    "  settings: {",
    "    redactSensitiveLogs: true,",
    "    interceptSensitiveLeakRequests: true,",
    "  },",
    "  schema: {"
  ];

  for (const variable of report.variables) {
    lines.push(...renderVariable(variable));
  }

  lines.push("  },", "});", "");
  return lines.join("\n");
}

function renderVariable(variable) {
  const type = dmnoTypeFor(variable.name);
  const dmnoType = type === "string" ? "DmnoBaseTypes.string" : `DmnoBaseTypes.${type}`;
  const description = `${sourceSummary(variable)} ${variable.notes.join(" ")}`.trim();
  const lines = [
    `    ${variable.name}: {`,
    `      extends: ${dmnoType},`,
    `      required: ${variable.required ? "true" : "false"},`
  ];
  if (variable.sensitivity === "secret") lines.push("      sensitive: true,");
  if (variable.visibility === "public") lines.push("      dynamic: false,");
  lines.push(`      description: '${escapeString(description)}',`);
  lines.push("    },");
  return lines;
}

function sourceSummary(variable) {
  const files = [...new Set(variable.sources.map((source) => source.file))].slice(0, 4);
  const suffix = variable.sources.length > 4 ? " and more" : "";
  return `Detected in ${files.join(", ")}${suffix}.`;
}

function escapeString(value) {
  return value.replace(/\\/g, "\\\\").replace(/'/g, "\\'");
}

